### ISSUE TITLE
Menambahkan field route_id pada view

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/opnsynid-stock-logistics-warehouse#5]
Todo:
- [ ] Tambahkan field route_id pd tree
- [ ] Tambahkan group berdasarkan route_id

**Comment by mikevhe18** [comment]
@andhit_r mas ini di modul apa ?

**Comment by andhit-r** [comment]
Mike modul apa yg diupdate lo liat di keterangan project (sebelah kanan, screenshot terlampir)

![modul_yang_dupdate](https://cloud.githubusercontent.com/assets/1947376/21832718/a23315c0-d7df-11e6-8b45-f103912394ae.png)
